// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_commerceApp.Shared.Data;

#nullable disable

namespace e_commerceApp.Shared.Migrations
{
    [DbContext(typeof(EcommDbContext))]
    [Migration("20241106084921_Datecreated")]
    partial class Datecreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("e_commerceApp.Shared.Models.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ab15d59c-7f65-472a-997a-bbb1bb9ca832",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "e7299d6a-b096-4b70-8312-4cf07e9cc139",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 49,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1974, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "MHSN27 MHSN",
                            PhoneNumber = "+1 1774867925"
                        },
                        new
                        {
                            Id = 2,
                            Age = 44,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1979, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Product Management",
                            FullName = "Sohel Shaikh",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            Id = 3,
                            Age = 43,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Public Relations (PR)",
                            FullName = "Mark Johnnah",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            Id = 4,
                            Age = 55,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1968, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Quality Assurance (QA)",
                            FullName = "JB _",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            Id = 5,
                            Age = 70,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1953, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Logistics",
                            FullName = "hugo sanchez",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            Id = 6,
                            Age = 70,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1953, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Administration",
                            FullName = "Zabi Rahmani",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            Id = 7,
                            Age = 60,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1963, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Training and Development",
                            FullName = "edimar lopes",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            Id = 8,
                            Age = 43,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Research and Development (R&D)",
                            FullName = "Arie melans",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            Id = 9,
                            Age = 53,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1970, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Product Management",
                            FullName = "Ziya Çetinkaya",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            Id = 10,
                            Age = 18,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Public Relations (PR)",
                            FullName = "Thiago Paiva Medeiros",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            Id = 11,
                            Age = 56,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1967, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Facilities Management",
                            FullName = "Thanh Nguyen",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            Id = 12,
                            Age = 39,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1984, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Rahul Salokhe",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            Id = 13,
                            Age = 23,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            FullName = "Jing Tarng Loke",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            Id = 14,
                            Age = 36,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources (HR)",
                            FullName = "met it",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            Id = 15,
                            Age = 50,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1973, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Research and Development (R&D)",
                            FullName = "Md.Ariful Islam",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            Id = 16,
                            Age = 47,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1976, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Legal",
                            FullName = "Mo Canada",
                            PhoneNumber = "+1 1824118974"
                        },
                        new
                        {
                            Id = 17,
                            Age = 26,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Administration",
                            FullName = "Altanzurkh T",
                            PhoneNumber = "+1 6395646874"
                        },
                        new
                        {
                            Id = 18,
                            Age = 72,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1951, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Public Relations (PR)",
                            FullName = "Mustafa YILDIZ",
                            PhoneNumber = "+1 1375269492"
                        },
                        new
                        {
                            Id = 19,
                            Age = 64,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1959, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Quality Assurance (QA)",
                            FullName = "Arief Fauzi",
                            PhoneNumber = "+1 3458476129"
                        },
                        new
                        {
                            Id = 20,
                            Age = 72,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1951, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "salvador castillo",
                            PhoneNumber = "+1 4486306495"
                        },
                        new
                        {
                            Id = 21,
                            Age = 62,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1961, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Training and Development",
                            FullName = "Luis TC",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            Id = 22,
                            Age = 32,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1991, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Adeel Baig",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            Id = 23,
                            Age = 52,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1971, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Information Technology (IT)",
                            FullName = "Novrita Inkac",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            Id = 24,
                            Age = 57,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1966, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Data Analytics",
                            FullName = "Felipe Rodríguez",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            Id = 25,
                            Age = 30,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Legal",
                            FullName = "Fabian Cebreros",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            Id = 26,
                            Age = 53,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1970, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Customer Support",
                            FullName = "Alan Michas",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            Id = 27,
                            Age = 66,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1957, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Administration",
                            FullName = "Lucky D.Bog",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            Id = 28,
                            Age = 55,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1968, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Research and Development (R&D)",
                            FullName = "Anunu",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            Id = 29,
                            Age = 26,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Product Management",
                            FullName = "KRAK 08",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            Id = 30,
                            Age = 47,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1976, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Customer Support",
                            FullName = "Boonsit Chanpoempoonpol",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            Id = 31,
                            Age = 44,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1979, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Business Development",
                            FullName = "Danilo Romao",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            Id = 32,
                            Age = 24,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1999, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Logistics",
                            FullName = "User 4571",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            Id = 33,
                            Age = 47,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1976, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Information Technology (IT)",
                            FullName = "Yuri Svyrydov",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            Id = 34,
                            Age = 37,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Procurement",
                            FullName = "Omar Abdelrahim",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            Id = 35,
                            Age = 30,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Quality Assurance (QA)",
                            FullName = "ADIAN Jan",
                            PhoneNumber = "+1 1824118974"
                        },
                        new
                        {
                            Id = 36,
                            Age = 20,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Thiago Valim",
                            PhoneNumber = "+1 6395646874"
                        },
                        new
                        {
                            Id = 37,
                            Age = 43,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Facilities Management",
                            FullName = "ศุภชัย สมพานิช",
                            PhoneNumber = "+1 1375269492"
                        },
                        new
                        {
                            Id = 38,
                            Age = 48,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Customer Support",
                            FullName = "ArTWorK211",
                            PhoneNumber = "+1 3458476129"
                        },
                        new
                        {
                            Id = 39,
                            Age = 69,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1954, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Information Technology (IT)",
                            FullName = "Johny Angsana",
                            PhoneNumber = "+1 4486306495"
                        },
                        new
                        {
                            Id = 40,
                            Age = 66,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1957, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Administration",
                            FullName = "kommineni narendra",
                            PhoneNumber = "+1 1774867925"
                        },
                        new
                        {
                            Id = 41,
                            Age = 52,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1971, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Procurement",
                            FullName = "Felipe Ramos",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            Id = 42,
                            Age = 25,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            FullName = "Maroine Chérif",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            Id = 43,
                            Age = 37,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Sana Ullah",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            Id = 44,
                            Age = 50,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1973, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Public Relations (PR)",
                            FullName = "michel akebo",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            Id = 45,
                            Age = 42,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1981, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Logistics",
                            FullName = "عمر العمودي Omar Al-Amoudi",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            Id = 46,
                            Age = 20,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Business Development",
                            FullName = "Louay Abdel Maeen",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            Id = 47,
                            Age = 56,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1967, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Black-Gold Sarnaut",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            Id = 48,
                            Age = 55,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1968, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "gueye abdoulaye",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            Id = 49,
                            Age = 34,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1989, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            FullName = "Cristian Ferreira",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            Id = 50,
                            Age = 51,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1972, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Amir Osama",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            Id = 51,
                            Age = 58,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources (HR)",
                            FullName = "Mihai Moisei",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            Id = 52,
                            Age = 18,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Procurement",
                            FullName = "AKHOM ALY",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            Id = 53,
                            Age = 52,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1971, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Customer Support",
                            FullName = "Banpote Jaruboon",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            Id = 54,
                            Age = 61,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1962, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Abdul Razak Abdulai",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            Id = 55,
                            Age = 22,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Product Management",
                            FullName = "ELy moussa",
                            PhoneNumber = "+1 1824118974"
                        },
                        new
                        {
                            Id = 56,
                            Age = 40,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1983, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Facilities Management",
                            FullName = "peter tharwat",
                            PhoneNumber = "+1 6395646874"
                        },
                        new
                        {
                            Id = 57,
                            Age = 38,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "william programer (CLASH OF CLAN)",
                            PhoneNumber = "+1 1375269492"
                        },
                        new
                        {
                            Id = 58,
                            Age = 54,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1969, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Luis Correa",
                            PhoneNumber = "+1 3458476129"
                        },
                        new
                        {
                            Id = 59,
                            Age = 58,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Product Management",
                            FullName = "Michael Chizoba",
                            PhoneNumber = "+1 4486306495"
                        },
                        new
                        {
                            Id = 60,
                            Age = 18,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2005, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Quality Assurance (QA)",
                            FullName = "Abdul-Rouf Ammar",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            Id = 61,
                            Age = 23,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Norbert Saint Georges",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            Id = 62,
                            Age = 19,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2004, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Research and Development (R&D)",
                            FullName = "trieuvnh",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            Id = 63,
                            Age = 60,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1963, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Procurement",
                            FullName = "Amr Moh",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            Id = 64,
                            Age = 20,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Information Technology (IT)",
                            FullName = "Ton",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            Id = 65,
                            Age = 66,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1957, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Quality Assurance (QA)",
                            FullName = "Prathamesh Karande",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            Id = 66,
                            Age = 73,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1950, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources (HR)",
                            FullName = "MarianoT3",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            Id = 67,
                            Age = 34,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1989, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources (HR)",
                            FullName = "Rekzon Aborde",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            Id = 68,
                            Age = 43,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Information Technology (IT)",
                            FullName = "prottoy roy",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            Id = 69,
                            Age = 22,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Product Management",
                            FullName = "sahli SAHBI",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            Id = 70,
                            Age = 46,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1977, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Administration",
                            FullName = "Onur Hos",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            Id = 71,
                            Age = 45,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Data Analytics",
                            FullName = "Armando Villagomez",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            Id = 72,
                            Age = 35,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Facilities Management",
                            FullName = "Jesus Alberto Roque Ortiz",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            Id = 73,
                            Age = 59,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1964, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Facilities Management",
                            FullName = "Md Shahin Aktar",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            Id = 74,
                            Age = 65,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1958, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Customer Support",
                            FullName = "Антон Метелёв",
                            PhoneNumber = "+1 1824118974"
                        });
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CartegoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CartegoryId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductStatus")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartegoryId1");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.CartItem", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Order", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.OrderItem", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_commerceApp.Shared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Product", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Category", "Cartegory")
                        .WithMany("Products")
                        .HasForeignKey("CartegoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartegory");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Review", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_commerceApp.Shared.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("e_commerceApp.Shared.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("e_commerceApp.Shared.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
